/**
 * Type declarations for the Vite-built UI bundle (index.js).
 * The implementation lives in ui/src/lib.tsx — keep this file in sync with
 * the exports there. index.js is generated by `pnpm build` in ui/ and is
 * not committed; this file is.
 */

export interface ParquetAppProps {
  /** Server-relative path to the .parquet file, e.g. "/sites/dev/Shared Documents/data.parquet" */
  filePath: string;
  /** Fetches the raw bytes of a file (implemented with SPHttpClient by the shell). */
  fetchFile: (path: string) => Promise<ArrayBuffer>;
}

export interface ParquetAppHandle {
  update: (props: ParquetAppProps) => void;
  unmount: () => void;
}

export function mount(el: HTMLElement, props: ParquetAppProps): ParquetAppHandle;
